<a href="https://colab.research.google.com/github/Saulrega/EDA/blob/main/05_Pivot_tables_y_cross_tabulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Llamar los datos

In [ ]:
#Llamamos el set de datos publico 
Chicago_data = 'https://raw.githubusercontent.com/terranigmark/curso-analisis-exploratorio-datos-platzi/main/Traffic_Crashes1.csv'

In [ ]:
import pandas as pd

In [ ]:
Chicago_df=pd.read_csv(Chicago_data)

In [ ]:
Chicago_df.head()

,Unnamed: 0,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,...,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date_real
0,290702,9e97e92753166de921a0e87199513aa841142c6fbb3a1e...,JA154528,NaN,2017-02-14 10:00:00,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,...,0.0,1.0,0.0,10,3,2,42.001676,-87.666364,POINT (-87.666364005301 42.001675862416),2017-02-14
1,405524,e5fe82ab7757d630a7f79927113bc63b5bede0cda74665...,JC391213,NaN,2019-08-13 19:12:00,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,...,0.0,8.0,0.0,19,3,8,41.940041,-87.650923,POINT (-87.650923222567 41.940040917032),2019-08-13
2,261834,8c8ea6db9e1950765419429e2732ba5598fc6f87ac9e0c...,JC273287,NaN,2019-05-22 08:30:00,25,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,4,5,41.955854,-87.710645,POINT (-87.710644534923 41.955853610383),2019-05-22
3,38519,02671b7d36a9d189d607778816fec23bbb2e5ac3cd3039...,JA307115,NaN,2017-06-14 16:50:00,0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,...,0.0,2.0,0.0,16,4,6,41.863734,-87.676313,POINT (-87.676312689993 41.863734390899),2017-06-14
4,420197,ef1b1d450f65c6d16245dffdd3304d93b8be7d7bbf47f3...,JB247942,NaN,2018-05-03 08:35:00,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,5,5,41.851794,-87.695223,POINT (-87.695223114296 41.851794251516),2018-05-03

*Transformaciones * básicas

In [ ]:
Chicago_df['CRASH_DATE'] = Chicago_df['CRASH_DATE'].apply(lambda x: pd.to_datetime(x,errors='coerce', utc=True))

In [ ]:
Chicago_df.groupby(['LIGHTING_CONDITION','REPORT_TYPE','CRASH_HOUR']).agg({'BEAT_OF_OCCURRENCE':'sum',})

                                                          BEAT_OF_OCCURRENCE
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                      1614.0
                   NOT ON SCENE (DESK REPORT) 0                      64739.0
                                              1                      60086.0
                                              2                      36251.0
                                              3                      39172.0
...                                                                      ...
UNKNOWN            ON SCENE                   19                      4735.0
                                              20                      8113.0
                                              21                      6122.0
                                              22                      9699.0
                                              23                      3176.0

[291 rows x 1 columns]

In [ ]:
table = pd.pivot_table(Chicago_df, index =["LIGHTING_CONDITION","REPORT_TYPE"])

In [ ]:
 Chicago_df.filter(["REPORT_TYPE","CRASH_DAY_OF_WEEK"],axis=1)

                      REPORT_TYPE  CRASH_DAY_OF_WEEK
0      NOT ON SCENE (DESK REPORT)                  3
1                        ON SCENE                  3
2                        ON SCENE                  4
3                        ON SCENE                  4
4      NOT ON SCENE (DESK REPORT)                  5
...                           ...                ...
27956                    ON SCENE                  1
27957  NOT ON SCENE (DESK REPORT)                  7
27958                    ON SCENE                  4
27959  NOT ON SCENE (DESK REPORT)                  5
27960  NOT ON SCENE (DESK REPORT)                  3

[27961 rows x 2 columns]

In [ ]:
cross_table=pd.crosstab(Chicago_df["REPORT_TYPE"], Chicago_df["REPORT_TYPE"])

In [ ]:
Chicago_df

,Unnamed: 0,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,...,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date_real
0,290702,9e97e92753166de921a0e87199513aa841142c6fbb3a1e...,JA154528,NaN,2017-02-14 10:00:00+00:00,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,...,0.0,1.0,0.0,10,3,2,42.001676,-87.666364,POINT (-87.666364005301 42.001675862416),2017-02-14
1,405524,e5fe82ab7757d630a7f79927113bc63b5bede0cda74665...,JC391213,NaN,2019-08-13 19:12:00+00:00,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,...,0.0,8.0,0.0,19,3,8,41.940041,-87.650923,POINT (-87.650923222567 41.940040917032),2019-08-13
2,261834,8c8ea6db9e1950765419429e2732ba5598fc6f87ac9e0c...,JC273287,NaN,2019-05-22 08:30:00+00:00,25,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,4,5,41.955854,-87.710645,POINT (-87.710644534923 41.955853610383),2019-05-22
3,38519,02671b7d36a9d189d607778816fec23bbb2e5ac3cd3039...,JA307115,NaN,2017-06-14 16:50:00+00:00,0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,...,0.0,2.0,0.0,16,4,6,41.863734,-87.676313,POINT (-87.676312689993 41.863734390899),2017-06-14
4,420197,ef1b1d450f65c6d16245dffdd3304d93b8be7d7bbf47f3...,JB247942,NaN,2018-05-03 08:35:00+00:00,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,5,5,41.851794,-87.695223,POINT (-87.695223114296 41.851794251516),2018-05-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27956,260197,8b8091d6e859b6e3d5b4945c48cc37f70cc5a0bb96cee5...,JC358154,NaN,2019-07-21 09:40:00+00:00,20,NO CONTROLS,OTHER,RAIN,DAYLIGHT,...,0.0,4.0,0.0,9,1,7,42.015524,-87.670149,POINT (-87.670148618764 42.015524050154),2019-07-21
27957,287015,9c4fd6d0e2aad82586cbfd9c324bd02e91bac1cab8a6d7...,JB260573,NaN,2018-05-12 09:30:00+00:00,30,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,...,0.0,2.0,0.0,9,7,5,41.714086,-87.644470,POINT (-87.644470094837 41.714086293399),2018-05-12
27958,45454,06a7b3fd12824e33a1e60c1e153da14eff3b4fdcf2974b...,JB470083,NaN,2018-10-10 13:25:00+00:00,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,1.0,0.0,13,4,10,41.768458,-87.682095,POINT (-87.682094956182 41.768457638793),2018-10-10
27959,278265,96dcaa7c132e400472e55cf6a22d2805e7ef9ea2b24183...,JC246583,NaN,2019-05-02 09:45:00+00:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,2.0,0.0,9,5,5,41.691385,-87.720232,POINT (-87.720231718762 41.691384555796),2019-05-02
27960,351224,c40cfbdecdb69787d725adbf4c6bf3ce4d937631c0624d...,JA382962,Y,2017-08-08 10:00:00+00:00,15,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,...,0.0,1.0,0.0,10,3,8,41.821304,-87.624922,POINT (-87.624922436047 41.821303995837),2017-08-08

In [ ]:
pd.crosstab(Chicago_df["TRAFFIC_CONTROL_DEVICE"],
            Chicago_df["WEATHER_CONDITION"],
            margins=True,
            margins_name="LIGHTING_CONDITION")

WEATHER_CONDITION,BLOWING SNOW,CLEAR,CLOUDY/OVERCAST,FOG/SMOKE/HAZE,FREEZING RAIN/DRIZZLE,OTHER,RAIN,SEVERE CROSS WIND GATE,SLEET/HAIL,SNOW,UNKNOWN,LIGHTING_CONDITION
TRAFFIC_CONTROL_DEVICE,,,,,,,,,,,,
DELINEATORS,0,5,2,0,0,0,1,0,0,0,3,11
FLASHING CONTROL SIGNAL,0,3,0,0,0,0,1,0,0,0,0,4
LANE USE MARKING,0,62,1,0,0,2,4,0,0,1,4,74
NO CONTROLS,2,13084,473,31,14,46,1274,8,18,546,687,16183
NO PASSING,0,0,0,0,0,0,1,0,0,0,0,1
OTHER,0,121,6,0,0,0,17,0,2,9,11,166
OTHER RAILROAD CROSSING,0,6,0,0,0,0,1,0,0,0,0,7
OTHER REG. SIGN,0,19,2,0,0,0,2,0,0,2,0,25
OTHER WARNING SIGN,0,18,0,0,0,0,6,0,0,0,0,24
PEDESTRIAN CROSSING SIGN,0,7,1,0,0,0,2,0,0,1,0,11
POLICE/FLAGMAN,0,11,1,0,0,0,3,0,0,0,0,15
RAILROAD CROSSING GATE,0,14,0,0,0,0,3,0,0,0,0,17
RR CROSSING SIGN,0,1,0,0,0,0,0,0,0,0,1,2
SCHOOL ZONE,0,6,0,0,0,0,2,0,0,0,0,8
STOP SIGN/FLASHER,0,2103,116,4,2,11,266,0,8,130,63,2703
TRAFFIC SIGNAL,0,6284,244,16,11,21,795,3,8,231,138,7751
UNKNOWN,0,482,13,1,0,5,54,0,0,25,341,921
YIELD,0,34,0,0,0,1,0,0,0,2,1,38
LIGHTING_CONDITION,2,22260,859,52,27,86,2432,11,36,947,1249,27961

In [ ]:
pd.crosstab(Chicago_df["TRAFFIC_CONTROL_DEVICE"], Chicago_df["WEATHER_CONDITION"],normalize=True).head(10)

WEATHER_CONDITION,BLOWING SNOW,CLEAR,CLOUDY/OVERCAST,FOG/SMOKE/HAZE,FREEZING RAIN/DRIZZLE,OTHER,RAIN,SEVERE CROSS WIND GATE,SLEET/HAIL,SNOW,UNKNOWN
TRAFFIC_CONTROL_DEVICE,,,,,,,,,,,
DELINEATORS,0.000000,0.000179,0.000072,0.000000,0.000000,0.000000,0.000036,0.000000,0.000000,0.000000,0.000107
FLASHING CONTROL SIGNAL,0.000000,0.000107,0.000000,0.000000,0.000000,0.000000,0.000036,0.000000,0.000000,0.000000,0.000000
LANE USE MARKING,0.000000,0.002217,0.000036,0.000000,0.000000,0.000072,0.000143,0.000000,0.000000,0.000036,0.000143
NO CONTROLS,0.000072,0.467937,0.016916,0.001109,0.000501,0.001645,0.045563,0.000286,0.000644,0.019527,0.024570
NO PASSING,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000036,0.000000,0.000000,0.000000,0.000000
OTHER,0.000000,0.004327,0.000215,0.000000,0.000000,0.000000,0.000608,0.000000,0.000072,0.000322,0.000393
OTHER RAILROAD CROSSING,0.000000,0.000215,0.000000,0.000000,0.000000,0.000000,0.000036,0.000000,0.000000,0.000000,0.000000
OTHER REG. SIGN,0.000000,0.000680,0.000072,0.000000,0.000000,0.000000,0.000072,0.000000,0.000000,0.000072,0.000000
OTHER WARNING SIGN,0.000000,0.000644,0.000000,0.000000,0.000000,0.000000,0.000215,0.000000,0.000000,0.000000,0.000000
PEDESTRIAN CROSSING SIGN,0.000000,0.000250,0.000036,0.000000,0.000000,0.000000,0.000072,0.000000,0.000000,0.000036,0.000000

In [ ]:
pd.melt(Chicago_df, id_vars=['TRAFFIC_CONTROL_DEVICE'], value_vars=['WEATHER_CONDITION'])

      TRAFFIC_CONTROL_DEVICE           variable            value
0                NO CONTROLS  WEATHER_CONDITION            CLEAR
1             TRAFFIC SIGNAL  WEATHER_CONDITION            CLEAR
2          STOP SIGN/FLASHER  WEATHER_CONDITION             RAIN
3                    UNKNOWN  WEATHER_CONDITION          UNKNOWN
4                NO CONTROLS  WEATHER_CONDITION             RAIN
...                      ...                ...              ...
27956            NO CONTROLS  WEATHER_CONDITION             RAIN
27957            NO CONTROLS  WEATHER_CONDITION  CLOUDY/OVERCAST
27958      STOP SIGN/FLASHER  WEATHER_CONDITION             RAIN
27959         TRAFFIC SIGNAL  WEATHER_CONDITION             RAIN
27960            NO CONTROLS  WEATHER_CONDITION            CLEAR

[27961 rows x 3 columns]