<a href="https://colab.research.google.com/github/Saulrega/EDA/blob/main/10_Weather_Regresion_y_evaluacion_de_hipotesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url='https://raw.githubusercontent.com/terranigmark/curso-analisis-exploratorio-datos-platzi/main/weatherHistory.csv'

Leyendo el data set

In [2]:
import pandas as pd
data= pd.read_csv(url)

In [3]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [4]:
data.head()
data.fillna(0,inplace=True)

In [5]:
data["Daily Summary"] = data["Daily Summary"].astype('category')
data["Daily Summary_cat"] = data["Daily Summary"].cat.codes

In [6]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Daily Summary_cat
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,197
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,197
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,197
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,197
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,197

In [7]:
# Neural Network Regression
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [8]:
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Temperature (C),96453.0,11.932678,9.551546,-21.822222,4.688889,12.0000,18.838889,39.905556
Apparent Temperature (C),96453.0,10.855029,10.696847,-27.716667,2.311111,12.0000,18.838889,39.344444
Humidity,96453.0,0.734899,0.195473,0.000000,0.600000,0.7800,0.890000,1.000000
Wind Speed (km/h),96453.0,10.810640,6.913571,0.000000,5.828200,9.9659,14.135800,63.852600
Wind Bearing (degrees),96453.0,187.509232,107.383428,0.000000,116.000000,180.0000,290.000000,359.000000
Visibility (km),96453.0,10.347325,4.192123,0.000000,8.339800,10.0464,14.812000,16.100000
Loud Cover,96453.0,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
Pressure (millibars),96453.0,1003.235956,116.969906,0.000000,1011.900000,1016.4500,1021.090000,1046.380000
Daily Summary_cat,96453.0,129.308057,56.275398,0.000000,95.000000,118.0000,181.000000,213.000000

In [9]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Daily Summary_cat
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,197
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,197
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,197
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,197
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,197

In [10]:
target_column = ['Summary'] 
descritores=['Temperature (C)','Humidity','Visibility (km)']

In [11]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary', 'Daily Summary_cat'],
      dtype='object')

In [12]:
descritores

['Temperature (C)', 'Humidity', 'Visibility (km)']

In [13]:
X = data[descritores].values
y = data[target_column].values
# división de los datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(67517, 3)
(28936, 3)

In [14]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predict_test))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

                                     precision    recall  f1-score   support

                             Breezy       0.00      0.00      0.00        17
                   Breezy and Foggy       0.00      0.00      0.00        15
           Breezy and Mostly Cloudy       0.00      0.00      0.00       163
                Breezy and Overcast       0.00      0.00      0.00       150
           Breezy and Partly Cloudy       0.00      0.00      0.00       118
                              Clear       0.58      0.04      0.07      3279
Dangerously Windy and Partly Cloudy       0.00      0.00      0.00         1
                            Drizzle       0.00      0.00      0.00        15
                                Dry       0.00      0.00      0.00        11
              Dry and Mostly Cloudy       0.00      0.00      0.00         5
              Dry and Partly Cloudy       0.00      0.00      0.00        24
                              Foggy       0.98      1.00      0.99      2117
            Humid and Mostly Cloudy       0.00      0.00      0.00        10
                 Humid and Overcast       0.00      0.00      0.00         1
            Humid and Partly Cloudy       0.00      0.00      0.00         5
                         Light Rain       0.33      0.05      0.09        20
                      Mostly Cloudy       0.38      0.41      0.40      8575
                           Overcast       0.46      0.39      0.42      4910
                      Partly Cloudy       0.47      0.65      0.55      9445
                               Rain       0.00      0.00      0.00         4
                              Windy       0.00      0.00      0.00         3
            Windy and Mostly Cloudy       0.00      0.00      0.00        11
                 Windy and Overcast       0.00      0.00      0.00        15
            Windy and Partly Cloudy       0.00      0.00      0.00        22

                           accuracy                           0.48     28936
                          macro avg       0.13      0.11      0.10     28936
                       weighted avg       0.48      0.48      0.45     28936

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [16]:
print(confusion_matrix(y_test,predict_test))

[[   0    0    0    0    0    3    0    0    0    0    0    0    0    0
     0    0    4    2    8    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0   15    0    0
     0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0   85    1   77    0    0    0    0    0]
 [   0    0    0    0    0    1    0    0    0    0    0    1    0    0
     0    0   74   28   46    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0   35    0   83    0    0    0    0    0]
 [   0    0    0    0    0  119    0    0    0    0    0    6    0    0
     0    0  879  484 1791    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    1    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    6    0    0
     0    0    4    2    3    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   11    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    5    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   24    0    0    0    0    0]
 [   0    0    0    0    0    3    0    0    0    0    0 2114    0    0
     0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    7    0    3    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    4    0    1    0    0    0    0    0]
 [   0    0    0    0    0    2    0    0    0    0    0    1    0    0
     0    1   10    5    1    0    0    0    0    0]
 [   0    0    0    0    0   25    0    0    0    0    0    8    0    0
     0    0 3532 1048 3962    0    0    0    0    0]
 [   0    0    0    0    0   14    0    0    0    0    0   12    0    0
     0    0 2072 1939  873    0    0    0    0    0]
 [   0    0    0    0    0   37    0    0    0    0    0    1    0    0
     0    0 2534  710 6163    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    2    0    2    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    2    0    1    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    8    0    3    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    7    6    2    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    9    0   13    0    0    0    0    0]]